### ISSUE TITLE
Unable to spawn ./run due to permission denied

### ISSUE THREAD

**Issue by Adagis-MC** [thespad/docker-get_iplayer#35]
Getting the following log errors on Docker tag version: v3.30-spad003
s6-supervise get_iplayer/log: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise get_iplayer/log (child): fatal: unable to exec run: Permission denied
s6-supervise get_iplayer_web/log: warning: unable to spawn ./run - waiting 10 seconds

**Comment by thespad** [comment]
Just tested with a clean install and I can't replicate.

What arch/os/docker version are you running?

**Comment by Adagis-MC** [comment]
Hi, Yes, it's kernel 3.10.108
